services:
  nginx:
    container_name: neuro_nginx
    image: nginx:1.27-alpine
    restart: always
    volumes:
      - "./:/var/www:cached"
      - "./config/certs/:/etc/nginx/certs"
      - "./config/nginx/${ENV}.conf:/etc/nginx/conf.d/default.conf"
    networks:
      default:
        ipv4_address: 172.26.0.11
    ports:
      - 80:80
      - 443:443
  backend:
    container_name: neuro_backend
    build:
      context: "./src/hti6-backend"
      dockerfile: Dockerfile
    restart: always
    volumes:
      - "./config/php/php.ini:/usr/local/etc/php/php.ini"
      - "./src/hti6-backend:/var/www:cached"
      - "./src/hti6-backend/env-${ENV}:/var/www/.env:cached"
    working_dir: /var/www
    networks:
      default:
        ipv4_address: 172.26.0.12
  postgres:
    container_name: neuro_postgres
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - "postgres:/var/lib/postgresql/data"
    networks:
      default:
        ipv4_address: 172.26.0.13
  redis:
    container_name: neuro_redis
    image: redis:latest
    restart: always
    volumes:
      - "/var/www/redis:/root/redis"
      - "/var/www/redis/redis.conf:/usr/local/etc/redis/redis.conf"
    environment:
      REDIS_PASSWORD: root
    networks:
      default:
        ipv4_address: 172.26.0.14
networks:
  default:
    driver: bridge
    name: neuro_bridge
    ipam:
      config:
        - subnet: 172.26.0.0/24
volumes:
  postgres:
    name: neuro_postgres
    external: false