services:
  nginx:
    container_name: neuro_nginx
    image: nginx:1.27-alpine
    restart: always
    volumes:
      - "./:/var/www:cached"
      - "./config/certs/:/etc/nginx/certs"
      - "./config/nginx/${ENV}.conf:/etc/nginx/conf.d/default.conf"
    networks:
      default:
        ipv4_address: 172.26.0.11
    ports:
      - 80:80
      - 443:443
  backend:
    container_name: neuro_backend
    build:
      context: "./src/hti6-backend"
      dockerfile: Dockerfile
    restart: always
    volumes:
      - "./config/php/php.ini:/usr/local/etc/php/php.ini"
      - "./src/hti6-backend:/var/www:cached"
      - "./src/hti6-backend/env-${ENV}:/var/www/.env:cached"
    working_dir: /var/www
    networks:
      default:
        ipv4_address: 172.26.0.12
  postgres:
    container_name: neuro_postgres
    image: postgis/postgis:17-3.5-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - "postgres:/var/lib/postgresql/data"
    networks:
      default:
        ipv4_address: 172.26.0.13
  redis:
    container_name: neuro_redis
    image: redis:latest
    restart: always
    volumes:
      - "/var/www/redis:/root/redis"
      - "/var/www/redis/redis.conf:/usr/local/etc/redis/redis.conf"
    environment:
      REDIS_PASSWORD: root
    networks:
      default:
        ipv4_address: 172.26.0.14
  supervisor:
    container_name: neuro_supervisor
    restart: always
    build:
      context: ./config/supervisor
      dockerfile: Dockerfile
    volumes:
      - "./src/hti6-backend:/var/www:cached"
      - "./src/hti6-backend/env-${ENV}:/var/www/.env:cached"
      - "./config/supervisor/default.conf:/etc/supervisor/supervisord.conf"
    networks:
      default:
        ipv4_address: 172.26.0.15
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.26.0.15:9092,PLAINTEXT_INTERNAL://172.26.0.15:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "images:1:1"
    networks:
      default:
        ipv4_address: 172.26.0.15
networks:
  default:
    driver: bridge
    name: neuro_bridge
    ipam:
      config:
        - subnet: 172.26.0.0/24
volumes:
  postgres:
    name: neuro_postgres
    external: false